public class BackupInfoBean {
  /*   class ResultClass {
        public String FakeResult;
    }
    
    List<ResultClass> results = new List<ResultClass>();
    
    String j = '{\"Result\": [{\"FakeResult\" : \"NothingToSeeHere\"},{\"FakeResult\" : \"NothingToSeeHere\"}],\"Status\":\"OK\"}';
    
    Map<String, Object> tmpResult = (Map<String, Object>) JSON.deserializeUntyped(j);
    
    List<Object> resultList = (List<Object>)(tmpResult.get('Result'));
    
    for (Object entry : resultList) {
        results.add((ResultClass)(JSON.deserialize(JSON.serialize(entry), ResultClass.class)));
    }
    System.debug(results.get(0).FakeResult);*/
}